### PR TITLE
Ch114/random initialization

### PR DESCRIPTION
**Pull request by starakaj**
Nothing fancy, just read all of the input pins and use their least significant to build up a 16 bit random seed. It's not perfect but it should be a bit different each time.

### CODE REVIEW

**Review by maxardito — CHANGES_REQUESTED** [review]
Love it! Only suggestion is I wonder if `makeRandomSeed()` should be defined in globals.h, what do you think?

**Comment by starakaj** [comment]
I understand the reasoning but I don't think it can be since it needs
hardware.

-S

**Comment by maxardito** [comment]
ohhh you're right, sweet sweet, I'm gonna merge

**Comment by starakaj** [comment]
Hell yeah.

**Pull request merged**
